<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>taskpaper</string>
		<string>tp</string>
	</array>
	<key>name</key>
	<string>Taskpaper</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^.*@done.*$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag_parameter.due.taskpaper</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=\s)@due(\([^)]*\)){0,1}</string>
			<key>name</key>
			<string>entity.name.tag.due.taskpaper</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag_parameter.start.taskpaper</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=\s)@start(\([^)]*\)){0,1}</string>
			<key>name</key>
			<string>entity.name.tag.start.taskpaper</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag_parameter.working.taskpaper</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=\s)@working(\([^)]*\)){0,1}</string>
			<key>name</key>
			<string>entity.name.tag.working.taskpaper</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag_parameter.today.taskpaper</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=\s)@today(\([^)]*\)){0,1}</string>
			<key>name</key>
			<string>entity.name.tag.today.taskpaper</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag_parameter.next.taskpaper</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=\s)@next(\([^)]*\)){0,1}</string>
			<key>name</key>
			<string>entity.name.tag.next.taskpaper</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>project</string>
			<key>match</key>
			<string>^.*:$</string>
			<key>name</key>
			<string>entity.name.function.project.taskpaper</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag_parameter.taskpaper</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>tag</string>
			<key>match</key>
			<string>(?&lt;=\s)@[^( \n]*(\([^)]*\)){0,1}</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.bold.taskpaper</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\*\*(.+)\*\*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic.taskpaper</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\*(.+)\*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#+.*</string>
			<key>name</key>
			<string>entity.name.function.header.markdown</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.taskpaper</string>
	<key>uuid</key>
	<string>57434a90-e4fd-446d-8910-cfbc584420c5</string>
</dict>
</plist>
